### ISSUE TITLE
Typo error in documentation

### ISSUE THREAD

**Issue by mauro-d** [mauro-d/summon-middleware#1]
Section -> Dinamically enable or disable express middleware
Content -> This wrapper allow you to dinamically enable or disable an express or connect middleware. In some circumstances you would use a middleware only if some conditions are met.

Change Content To -> This wrapper **allows** you to dinamically enable or disable an express or connect middleware. In some circumstances you would use a middleware only if some conditions are met.

**Comment by NickNaso** [comment]
Fixed typos in documentation as requested.
