### ISSUE TITLE
Add test case for error

### ISSUE THREAD

**Issue by mauro-d** [mauro-d/summon-middleware#3]
Add test case for exceptions thrown in [summon-middleware.js](https://github.com/mauro-d/summon-middleware/blob/master/lib/summon-middleware.js)

**Comment by NickNaso** [comment]
### Test case added to test suite
Added two test case to intercept the exceptions thrown. We control the following two case: 

-  Predicate parameter is not a function
-  Middleware parameter is not a function

All tests are executed and passed.
